[functions]
  directory = "functions"
  external_node_modules = ["mongodb", "http-status"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/leaderboard-list"
  status = 200

[[redirects]]
  from = '/*'
  to = '/.netlify/functions/:splat'
  status = 200
