name: pinball_models
description: The interface and models for an API providing access to Trending.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  meta: ^1.8.0

dev_dependencies:
  json_serializable: ^6.5.4
  test: ^1.22.0
